# Generated by Django 2.2.1 on 2019-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='udata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
                ('interest_in', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('username', models.IntegerField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
